official-repo: &official-repo
  DanySK/Course-DevOps-Introduction
language: minimal
addons:
  apt:
    update: true
    packages:
      # LaTeX decent font processor
      - cm-super
      # Image processing
      - inkscape
      # For git latexdiff
      - latexdiff
      # For Minted
      - python-pygments
      # LaTeX
      - texlive-base
      - texlive-bibtex-extra
      - texlive-extra-utils
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-generic-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-publishers
      - texlive-science
      # Debug
      - tree
env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - JDK="adopt@1.11"

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

script:
  - ./gradlew buildLatex
  - cd workspace
  - for dir in $(ls); do cd $dir; ./gradlew check || travis_terminate 1; cd ..; done
  - cd $TRAVIS_BUILD_DIR

before_deploy:
  - git config --local user.name "Danilo Pianini"
  - git config --local user.email "danilo.pianini@unibo.it"
  - $GRAVIS/autotag

before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_deploy:
    - tree

_deploy_base: &deploy_base
    provider: releases
    edge: true
    file: "*.pdf"

deploy:
  - <<: *deploy_base
    on:
      repo: *official-repo
      tags: true
  - <<: *deploy_base
    on:
      repo: *official-repo
      tags: false
